### ISSUE TITLE
The stage mananger window icon have outside the window.

### ISSUE THREAD

**Issue by linitfor** [awaescher/StageManager#1]
This is real good design for windows. Will you provide other configuration for this app.
I have try your project. The number window of stage manager might outside the window.
If we can limit the max number of icon, this problem can be solve.

**Comment by awaescher** [comment]
Yes, this is what I meant here.
Thanks for the feedback.
![image](https://user-images.githubusercontent.com/3630638/200646078-ee281801-12e5-4b12-96ba-fd8ae062e207.png)
