### ISSUE TITLE
App crash on interacting with tray icon

### ISSUE THREAD

**Issue by WaterResistantCoder** [awaescher/StageManager#14]
Device name	Happy-PC
Processor	AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

Edition	Windows 11 Pro
Version	22H2
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0

Recording: https://drive.google.com/file/d/10QsNEnKJjuD6RLvNFQdfK8NQdHc9yYPR/view?usp=sharing

**Comment by WaterResistantCoder** [comment]
Does not crash if ran thru `dotnet run --project StageManager`
For both main and trayicon branchs.

**Comment by SahajTC** [comment]
Yes Exact Same issue here. 
Even the mouse gets jammed for a moment after clicking the tray icon
Device name	Asus-Vivobook-X413
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	8.00 GB 
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎12-‎09-‎2023
OS build	23541.1000
Experience	Windows Feature Experience Pack 1000.23541.1000.0

**Comment by awaescher** [comment]
I can replicate the behavior, as you wrote, it does not happen when used with `dotnet run`.

My best guess is that the mouse hook I use to get the desktop wide mouse move recognition comes conflicts with the [hook of the tray icon](https://github.com/hardcodet/wpf-notifyicon/blob/4004e88ee272de094b9ae6a52908628b1533e708/src/NotifyIconWpf/Interop/WindowMessageSink.cs).
