### ISSUE TITLE
Trouble downloading

### ISSUE THREAD

**Issue by acrosrivera** [awaescher/StageManager#27]
Hello I'm very new to Github but wanted to try and use your StageManager app you have been working on however whenever I install the executable file I cannot run it. When I click on it in File Explorer, a prompt window opens asking me to open it with NotePad or other apps, but I cannot run the actual file. Any assistance would be much appreciated. :)

**Comment by acrosrivera** [comment]
Oh also, I think it's important to note that I have downloaded the dotnet 8.0 application and am running on windows 11

**Comment by acrosrivera** [comment]
I found that the solution was to go into File Explorer and change the file to .exe instead of .crdownload which is how it was being downloaded automatically gl to anyone with this issue :)

**Comment by awaescher** [comment]
.crdownload is an unfinished chrome download. Once the download is finished and verified, the browser renames this file. This is how the browser handles downloads and has nothing to do with GitHub or my app.

Anyway, good to see it's working for you. Have fun.
