### ISSUE TITLE
The Stage Manager with handle winodow policy 

### ISSUE THREAD

**Issue by linitfor** [awaescher/StageManager#3]
Hi  developer,

I have try your stage manager app. I found you have plan the scheme both drop window to secene and pull window from scene.
But your current scheme is only use pull window from scene.

I have try to re-managment your code with change the order first check "EnableWindowPullToScene" and then check "EnableWindowDropToScene". After the re-order the code sequence. You can both enable EnableWindowDropToScene and EnableWindowPullToScene to realize the both direction for user using. This schemem can be more intuitive. 

The other scheme I still cannot realize is drop the window to "a new scene" which is not the current existed scene. Will you add this function to enhance this app ?

**Comment by awaescher** [comment]
I started with drop to scene but found out that Apple only implemented pull to scene. If course both could be activated, I also think Apple will enable it too.

**Comment by linitfor** [comment]
I have successed to use your code to do that. If you need, I can send the code back to you.
I am happy to use your app on my current notbook. ^.^b
The only defect of this bidirection window management is that the drop window to secene cannot remember the first mouse press window location. When the Window of "drop window to secene"  is successfully combined into the other scene, the Window location will show on the "mouse release" location. You should move the "Window" back to your perference location again.
I am a C# new beginner.  I still try to learn the structure of how to re-manage the above condition.
If you can help to do that, I will really appreciate your help very much.

**Comment by awaescher** [comment]
I already got that managed saving a copy of the window location after each move that can be used after the drop.
However the issue with "drop to scene" was that the global mouse hook interfered with ordinary window focus clicks if they are close to the scenes and then - pop - the window was moved to another scene.
I was happy to disable that feature as I noticed Apple skips that one too.
