### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by Saadishigh** [awaescher/StageManager#5]
Hey. I have seen your work it's amazing but I can't run this on my pc. Can you help me out?

**Comment by awaescher** [comment]
Hey, hard to help you out without further information.
Does your system fulfill [the requirements](https://github.com/awaescher/StageManager#requirements)?

If it does, what's the error you're seeing?

**Comment by Saadishigh** [comment]
Yes bro I have github desktop installed and I have clone the repository.  I don't understand the other two steps can you attatch a video help guide. It will help a lot.

**Comment by awaescher** [comment]
If you cloned it, you have the files locally. Use a command line tool and navigate there and run `dotnet run --project StageManager`
I am not sure what steps you are referring to. Also, with requirements I did not mean GitHub desktop and cloning but having an adequate system and the .NET 6 SDK.

![grafik](https://user-images.githubusercontent.com/3630638/214262190-b4e897e0-1d3b-4e89-b272-a80030e11775.png)

Also once again ... what is the error you're seeing?
